### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by jokers-x** [Muehe/sqlua#1]
I want to use this software to export my Chinese database.

But I don't know what I should do after this step?

thx!

![qq 20170115182855](https://cloud.githubusercontent.com/assets/24637857/21961899/f61a53aa-db50-11e6-87b1-ddc5445832c7.png)

**Comment by Muehe** [comment]
`quests, npcs, obj, items = doExtract(cur)`

This command will create database files in your folder, as well as saving the classes to `quests, npcs, obj, items` in case you want to work/debug with them inside IDLE. If you want to know how this function works exactly you can see it in [main.py](https://github.com/Muehe/sqlua/blob/master/main.py). You also have to apply your user name and password for mysql in that file (line 16), if they are not both "mangos".

Currently this only produces files for ShaguQuest though. If you need them for Questie I'd advise waiting for its 4.0 version, as their DB structure is going to change significantly.

Hope this helps. If you have more questions feel free to ask. Note however that I might not be able to reply over the next week.

**Comment by jokers-x** [comment]
I'm trying to install your method.
But there was a mistake.
I don't know Python.
I just want to use this addons with my friends in the CWOW.
![qq 20170115192311](https://cloud.githubusercontent.com/assets/24637857/21962113/737dd96e-db58-11e6-87ad-61aa958b9a10.png)

**Comment by Muehe** [comment]
According to the lower part of the error messages it seems possible your DB format differs from the one cmangos used (note how it says "Unknown column 'minlevelhealth' in 'field list'"). If this is the problem you would have to edit the [NpcList.py](https://github.com/Muehe/sqlua/blob/master/NpcList.py#L49) in line 49 to match the field names in your database.

Might just be "MinLevelHealth" now, like in the current cmangos DB. Have not done a lot of work lately as I have had no internet at home for the last two month...

**Comment by jokers-x** [comment]
think a lot

**Comment by jokers-x** [comment]
I modified my database,But they have a new problem.
thaks.
![qq 20170427175417](https://cloud.githubusercontent.com/assets/24637857/25478248/fbbc7c94-2b72-11e7-96b5-79d6a71abc47.jpg)
I just want to use ShaguQuest in CWOW.

**Comment by Muehe** [comment]
Which database are you using? Can give it a try if you send me the link.

**Comment by jokers-x** [comment]
A Chinese database, I compare the mongoszero database has been restored a few table aliases.
Give me your email and I'll send it to you?

**Comment by Muehe** [comment]
Will have a look as soon as I have the time.

**Comment by jokers-x** [comment]
thanks

**Comment by jokers-x** [comment]
https://drive.google.com/open?id=0B2oEMmNXgQUyYlVIc2xCeWhEdk0
Wait until you have time to help.

**Comment by Muehe** [comment]
Hey, shagu published a version with a chinese DB today: https://github.com/shagu/ShaguQuest/releases

Could you give it a try and tell me if there are any errors?

**Comment by Muehe** [comment]
@jokers-x Hey there, sorry for taking a year, but I just added a commit which lets you extract a CMaNGOS DB which has a localisation.

Only way to use this feature at the moment is through IDLE with something like `quests.printQuestFile(locale='zhCN')`. Readme has also been updated.

P.S.: Check out [pfQuest](https://github.com/shagu/pfQuest/releases) if you haven't already.
